# This YAML is based on the structure provided in the Render documentation.

databases:
  - name: travel-app-db   # A name for the database service
    plan: free
    databaseName: travelappdb # The actual name of the database inside PostgreSQL
    user: travelappuser # The username for the database

services:
  - type: web
    plan: free
    name: travel-app-web # A name for your web service
    runtime: python
    buildCommand: './build.sh'
    # IMPORTANT: The start command is updated for your project's name 'alx_travel_app'
    # It uses wsgi.py, which is standard for Gunicorn.
    startCommand: 'gunicorn alx_travel_app.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: travel-app-db # This MUST match the database name above
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Let Render create a secure secret key for you
      - key: WEB_CONCURRENCY
        value: 4 # As recommended in the guide
      - key: DEBUG
        value: False # Always set DEBUG to False in production
