services:
  # 1. A PostgreSQL database for your app
  - type: pserv
    name: travel-app-db
    env: postgres # This is the correct way to specify the service type
    plan: free # Explicitly request the free plan
    databaseName: travelappdb
    user: travelappuser

  # 2. A Redis instance for your Celery tasks
  - type: pserv
    name: travel-app-redis
    env: redis # This specifies the service type as Redis
    plan: free # Explicitly request the free plan

  # 3. Your Django Web Service (runs Gunicorn)
  - type: web
    name: travel-app-web
    env: python
    plan: free # Explicitly request the free plan
    buildCommand: "./build.sh"
    startCommand: "gunicorn alx_travel_app.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: travel-app-db
          property: internalConnectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: travel-app-redis
          property: redisConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

  # 4. Your Celery Worker Service
  - type: worker
    name: travel-app-worker
    env: python
    plan: free # Explicitly request the free plan
    startCommand: "celery -A alx_travel_app worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: travel-app-db
          property: internalConnectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: travel-app-redis
          property: redisConnectionString
      - key: SECRET_KEY
        fromService:
          type: web
          name: travel-app-web
          envVarKey: SECRET_KEY
      - key: DEBUG
        value: False
